### ISSUE TITLE
Layouts with source from graphics content interface using incorrect path

### ISSUE THREAD

**Issue by jocado** [xnox/graphics-core22-samples#4]
Hi @xnox 

Currently when this snap is connected to the content interface from the nvidia-core22 snap, it fails to run apps:

```
# graphics-core22-samples.deviceQuery 
cannot update snap namespace: cannot use "/snap/graphics-core22-samples/5/graphics/X11/XErrorDB" as bind-mount source: not a directory
snap-update-ns failed with code 1
```

Seems to be because the path in the nvidia-core22 snap is actually:
- `$SNAP/usr/share/X11/XErrorDB`
not:
- `$SNAP/X11/XErrorDB`

I haven't created an MR with a suggested fix in this snap, because I'm not aware of all the details of the recent changes in the nvidia-core22 rework, and didn't want to assume anything.

It could be as sinple as updating the layout here:
```
layout:
  /usr/share/drirc.d:
    bind: $SNAP/graphics/usr/share/drirc.d
  /usr/share/X11/XErrorDB:
    bind: $SNAP/graphics/usr/share/X11/XErrorDB
  /usr/share/X11/locale:
    bind: $SNAP/graphics/usr/share/X11/locale
```

Cheers,
Just

**Comment by jocado** [comment]
It seems the paths from the context of the snap are actually different than I expected.

It looks like the content interface provider is now declaring some overlapping structure. Now the same files appear in multiple places.

```
slots:
  graphics-core22:
    interface: content
    source:
      read:
        # Required at the top-level by graphics-core22
        - $SNAP/bin
        - $SNAP/usr/share/drirc.d
        - $SNAP/usr/share/X11

        # Internal, pointed at by the above wrapper
        - $SNAP/etc
        - $SNAP/usr/lib
        - $SNAP/usr/share
```

So, actually, it looks like the layout in the samples snap is perhaps correct, and something off is going on due to the overlapping content interface structure ?
